### ISSUE TITLE
Is ellapsed a typo?

### ISSUE THREAD

**Issue by ghostfreak3000** [IndigoUnited/node-request-progress#13]
So in the Doc API it states to access the time elapsed via the variable.
`state.time.elapsed`
But the source code has `state.time.ellapsed`.
Is this a typo? or was the documentation wrong?

**Comment by satazor** [comment]
Oh crap, that is a time in the source code.. it should clearly be `elapsed`.. this will be a breaking change and I would need to bump the major version if we follow semver strictly here.. can you do a PR with the fixes in the source code and tests?

**Comment by ghostfreak3000** [comment]
let me fork and get to it

**Comment by satazor** [comment]
Cool, I will wait.

**Comment by ghostfreak3000** [comment]
Since the API is changing and we are following strict semver.. change to the major version then?

**Comment by satazor** [comment]
Your PR was published as 2.0.0.

**Comment by ghostfreak3000** [comment]
Great!
