### ISSUE TITLE
Save As Dialog

### ISSUE THREAD

**Issue by mateusmcg** [IndigoUnited/node-request-progress#16]
I don't know if this was already requested or not but it is possible to replace the:

    .pipe(fs.createWriteStream('doodle.png'))

for something like:

    .pipe(<open save-as dialog box for user to choose the location>);

Doesn't need to be exactly like this but i think you got the idea. Just to make things a little more 'fancy'.

**Comment by satazor** [comment]
Hmm I don't really know how this is related to `request-progress`?

**Comment by mateusmcg** [comment]
Since the request-progress has to save the file downloaded somewhere i was wondering if this feature was possible.

But if this is not of your interest that's no problem at all.

Thanks for the fast reply.

**Comment by satazor** [comment]
request-progress is simply a "addon"  to get feedback of the request itself. It's goal is to provide just that and nothing more. I suggest looking for some library that does what you want.
