### ISSUE TITLE
Not getting upload progress in google-api-nodejs-client

### ISSUE THREAD

**Issue by Akshay-Thakare** [IndigoUnited/node-request-progress#17]
I am trying to get upload progress using a request object. Could anyone suggest how to go about doing the same for an image upload.

I tried using request-progress module but it gets called only twice once at the start and once at the end of upload below is the code for the same.

```
var progress = require('request-progress');
progress(request_object).on('progress', function(state){
console.log('progress', state);
});
```

NOTE : I am working with `google-api-nodejs-client` so I only have a request object to get upload progress from.

**Comment by satazor** [comment]
request-progress only gives the download progress, that is clear in the README:

`Tracks the download progress of a request made with request, giving insight of various metrics including progress percentage, download speed and time remaining.`

**Comment by thunderkid** [comment]
Actually, perhaps you could make it a bit more explicit in the README that it won't work for upload progress. I was optimistically hoping that it would, but that you were emphasizing download because that's the more common case.

**Comment by satazor** [comment]
I think it is pretty clear, its right above de title: "Tracks the download progress"..

**Comment by thunderkid** [comment]
Perhaps the OP and I are just very optimistic people :)
I'm curious - would it be difficult to add upload progress tracking too, or is that too different to make sense in this project?

**Comment by satazor** [comment]
Well tracking upload would be a cool feature. If you or the OP wants to implement and its good enought, I will definitively merge it!

**Comment by thunderkid** [comment]
Perhaps I'll take a look. I'm currently tracking uploads with jQuery, using the following:
```
        $.ajax({
            type: 'PUT',
            url: url,
            data: blob,
            contentType: " ",  // Chrome needs space to leave contentType blank. If you put in "", it turns it into ",  text/plain ..."
            processData: false,
            success: () => { scrlog("uploaded ok"); onSuccess(); },
            xhr: () => {
                var xhr = new window.XMLHttpRequest();
                xhr.upload.addEventListener("progress", (evt: any) => { // omit upload for download progress
                    if (evt.lengthComputable) {
                        var fracComplete: number = evt.loaded / evt.total;
                        onProgress(fracComplete);
                    }
                }, false);

                return xhr;
            }
        }).fail(this.makeHttpErrorHandler("putBlob->"+url, onFail));
```
Would this type of approach work for `request-progress`? (I haven't looked inside your code at all yet.)

**Comment by satazor** [comment]
Yes it would be something similar but needs to integrate with request's module. Also I would keep thr same event structure if possible.
