### ISSUE TITLE
No changelog

### ISSUE THREAD

**Issue by sheerun** [IndigoUnited/node-request-progress#18]
Could you add a changelog at least for major releases?

**Comment by satazor** [comment]
Yes I can! Is there any tool that produces a changelog based on the commits that you could suggest?

**Comment by sheerun** [comment]
I guess the best technique for project on this scale, without highly structured commit messages, is just writing it by hand.. I can't recommend anything off the top of my head.

**Comment by satazor** [comment]
I will add a CHANGELOG from now on!
