### ISSUE TITLE
progress event doesn't fire

### ISSUE THREAD

**Issue by yoavapi** [IndigoUnited/node-request-progress#22]
using the code example but it seems not to be working.
any idea?

**Comment by satazor** [comment]
It works on my machine, what node version, OS, request version etc are you using?

**Comment by yoavapi** [comment]
OS X 10.11.5
node 6.2.1
request 2.72

**Comment by satazor** [comment]
Are you trying with `http://google.com/doodle.png`? It seems that image no longer exists.

**Comment by yoavapi** [comment]
I tried with a different URL and different mime types

**Comment by satazor** [comment]
This works for me with the same node version and I'm also using OSX:

```js
'use strict';

var request = require('request');
var progress = require('./');

progress(request('https://gitlab.com/xamiro/xcf-dist-windows/repository/archive.zip?ref=master', function (err) {
    console.log('finish!', err);
}))
.on('progress', console.log.bind(console, 'progress'))
.on('error', console.log.bind(console, 'error'))
.on('end', console.log.bind(console, 'end'));
```

Are you using a URL with big files? If the download is too fast, the `progress` event won't be fired. See `delay` and `throttle` options.

**Comment by satazor** [comment]
I've updated the URL above, the previous one wasn't reporting the `Content-Length` header

**Comment by yoavapi** [comment]
ok the updated url works -  thanks.

what about POST progress on upload files? supported?

**Comment by satazor** [comment]
No, see #17

**Comment by yoavapi** [comment]
Thanks, you may close this issue.
