### ISSUE TITLE
How can I access the response headers?

### ISSUE THREAD

**Issue by michahell** [IndigoUnited/node-request-progress#3]
So that the initial ```response.headers['content-length']``` can be stored and used as lookup value to get a better progress? Or is this not possible? can we get the response headers from ```request``` itself maybe? on(data)? 

In this ```http``` module example , we have access to the headers to determine wether or not it has a content-length property. One could then decide, based upon if the content-length property is there or not, to show progress:

https://gist.github.com/falkolab/f160f446d0bda8a69172

If I could do that with request-progress, that'd be great!

**Comment by satazor** [comment]
Yes you can. `request-progress` simply returns the original [`request`](https://github.com/request/request) instance. To access the headers, check the `response` event. You can see the documentation of it in the `request` module itself: https://github.com/request/request#streaming
