### ISSUE TITLE
Get download speed

### ISSUE THREAD

**Issue by constrom** [IndigoUnited/node-request-progress#4]
Is there an easy way to get the download speed ? 
Thanks for the package ;)

**Comment by satazor** [comment]
No at the moment, but it's easy to be implemented. We could add an average speed and instant speed metrics to the `state` object that already holds the `percentage`. I'm willing to accept a PR, what do you say?

**Comment by constrom** [comment]
There is no problems, i'll write it ;)

**Comment by satazor** [comment]
Thanks

**Comment by satazor** [comment]
Closing, feel free to make a PR if you will.
