### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by jviotti** [IndigoUnited/node-request-progress#9]
I have some thoughts about how to test this module:

1- Since the module never pipes `request` directly (only listens/emits events), we can easily mock it as an `EventEmitter` instance and avoid using the real `node-request` module (which could be accomplished with something like [nock](https://github.com/pgte/nock)).

2- The testing process will then go like this:

- Subscribe to the `progress` event.
- Set `throttle` to a value that basically cancels throttling, so we can get a `progress` event for each `data` we put in.
- Emit a `data` event and assert on the resulting `progress` state.

3- The `eta` calculation would be a little bit tricker to implement, given is time dependant. I've used [timekeeper](https://github.com/vesln/timekeeper) with success in situations similar to this. This module can be injected in the middle of the "emit data", "receive progress" cycle.

I also suggest going for black box unit testing for this module, since otherwise it'd require some refactoring to get started.

**Comment by satazor** [comment]
Looks good to me

**Comment by satazor** [comment]
As soon as we add some tests I will publish a new version with the eta support.

**Comment by satazor** [comment]
I've landed `0.4.0` with the `eta` + `lengthHeader` support. Still the unit tests are still very welcome. Thanks for your work.

**Comment by satazor** [comment]
Oops, closed by mistake

**Comment by satazor** [comment]
@jviotti any update on this?

**Comment by satazor** [comment]
I ended up doing the tests myself, by following your suggestions. Thanks!
